databases:
  - name: base-fedora-db
    region: ohio
    plan: free
    postgresMajorVersion: 14

services:
  - type: web
    name: base-fedora-web
    env: python
    region: ohio
    plan: free # base-fedora -- set to starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    healthCheckPath: /health_check/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: base-fedora-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: LOGLEVEL
        value: INFO
      - key: ADMIN_URL_PATH
        sync: false
      - key: POSTMARK_API_KEY
        sync: false
      # - key: REDIS_URL
      #   fromService:
      #     name: base-fedora-redis
      #     type: redis
      #     property: connectionString
      - key: LOGROCKET_APP_ID
        value: None # Leave None to disable LogRocket, or remove this env var altogether.


  # - type: worker
  #   name: base-fedora-celery
  #   plan: free
  #   region: ohio
  #   env: python
  #   buildCommand: "pip install -r requirements/production.txt"
  #   startCommand: "celery --app=config.celery worker --loglevel=INFO"

  # - type: redis
  #   name: base-fedora-redis
  #   region: ohio
  #   ipAllowList: [] # internal connections only
  #   plan: free # optional (defaults to starter)
