databases:
  - name: base-fedora-db
    region: ohio
    plan: free
    postgresMajorVersion: 14

envVarGroups:
  - name: base-fedora-env
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.8"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: LOGLEVEL
        value: INFO
      - key: ADMIN_URL_PATH
        sync: false
      - key: POSTMARK_API_KEY
        sync: false
      - key: EVENT_SECRET
        sync: false
      - key: AWS_S3_ACCESS_KEY_ID
        sync: false
      - key: AWS_S3_SECRET_ACCESS_KEY
        sync: false
    # - key: GNUPGHOME
    #   value: /opt/render/project/gnupg

services:
  - type: web
    name: base-fedora-web
    env: python
    region: ohio
    plan: free # base-fedora -- set to starter
    buildCommand: "./build-web.sh"
    startCommand: "gunicorn config.wsgi:application --access-logfile None"
    healthCheckPath: /health_check/
    envVars:
      - fromGroup: base-fedora-env
      - key: DATABASE_URL
        fromDatabase:
          name: base-fedora-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
      # - key: REDIS_URL
      #   fromService:
      #     name: base-fedora-redis
      #     type: redis
      #     property: connectionString

  # - type: worker
  #   name: base-fedora-celery
  #   plan: free  # base-fedora -- set to starter
  #   region: ohio
  #   env: python
  #   buildCommand: "./build-worker.sh"
  #   startCommand: "celery --app=config.celery worker --loglevel=INFO --concurrency 4"
  #   envVars:
  #     - fromGroup: base-fedora-env
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: base-fedora-db
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         name: base-fedora-redis
  #         type: redis
  #         property: connectionString

  # - type: redis
  #   name: base-fedora-redis
  #   region: ohio
  #   ipAllowList: [] # internal connections only
  #   plan: free # optional (defaults to starter)
