databases:
  - name: django-base-db
    region: ohio
    plan: free
    postgresMajorVersion: 15

envVarGroups:
  - name: django-base-env
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.1"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: LOGLEVEL
        value: INFO
      - key: ADMIN_URL_PATH
        sync: false
      - key: POSTMARK_API_KEY
        sync: false
      - key: EVENT_SECRET
        sync: false
      - key: AWS_S3_ACCESS_KEY_ID
        sync: false
      - key: AWS_S3_SECRET_ACCESS_KEY
        sync: false
    # - key: BACKUP_ENCRYPTION_PASSPHRASE
    #   sync: false
    #  - key: SOCIAL_AUTH_GOOGLE_CLIENT_ID
    #    sync: false
    #  - key: SOCIAL_AUTH_GOOGLE_CLIENT_SECRET
    #    sync: false

services:
  - type: web
    name: django-base-web
    env: python
    region: ohio
    plan: free # django-base -- set to starter
    buildCommand: "./build-web.sh"
    startCommand: "gunicorn config.wsgi:application --access-logfile None"
    healthCheckPath: /health_check/
    envVars:
      - fromGroup: django-base-env
      - key: DATABASE_URL
        fromDatabase:
          name: django-base-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
      # - key: REDIS_URL
      #   fromService:
      #     name: django-base-redis
      #     type: redis
      #     property: connectionString

  # - type: worker
  #   name: django-base-celery
  #   plan: free  # django-base -- set to starter
  #   region: ohio
  #   env: python
  #   buildCommand: "./build-worker.sh"
  #   startCommand: "celery --app=config.celery worker --loglevel=INFO --concurrency 4"
  #   envVars:
  #     - fromGroup: django-base-env
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: django-base-db
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         name: django-base-redis
  #         type: redis
  #         property: connectionString

  # - type: redis
  #   name: django-base-redis
  #   region: ohio
  #   ipAllowList: [] # internal connections only
  #   plan: free # optional (defaults to starter)
