# Generated by Django 4.2.17 on 2025-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="domain",
            field=models.CharField(
                default="example.com",
                help_text="The domain used to access the org on the web.",
                max_length=254,
            ),
            preserve_default=False,
        ),
    ]
