# Generated by Django 4.2.8 on 2024-01-15 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_locked",
        ),
    ]
