# Generated by Django 4.2.3 on 2023-07-26 21:01

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    m = apps.get_model
    Models = [
        m("core", "EmailMessage"),
        m("core", "EmailMessageWebhook"),
        m("core", "Event"),
        m("core", "Org"),
        m("core", "OrgInvitation"),
        m("core", "OrgUser"),
        m("core", "OrgUserOUSetting"),
        m("core", "OrgSetting"),
        m("core", "OUSetting"),
        m("core", "OUSettingDefault"),
        m("core", "OverriddenOrgSetting"),
        m("core", "Plan"),
        m("core", "PlanOrgSetting"),
    ]
    for Model in Models:
        for row in Model.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "20230709_remove_orguser_joined_at_emailmessage_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(
            gen_uuid, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
