# Generated by Django 4.2.3 on 2023-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "20230719_emailmessageattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="template_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
