# Generated by Django 4.2.3 on 2023-08-14 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "20230718_globalsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Secondary ID",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="email_message_attachments/")),
                ("filename", models.CharField(max_length=254)),
                ("mimetype", models.CharField(max_length=254)),
                (
                    "email_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.emailmessage",
                    ),
                ),
            ],
            options={
                "order_with_respect_to": "email_message",
            },
        ),
    ]
