# Generated by Django 3.2.10 on 2022-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_email_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
