# Generated by Django 3.2.13 on 2022-09-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_emailmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, default=None, help_text='Message-ID provided by the sending service as per RFC 5322', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('bounced', 'Bounced'), ('spam', 'Spam'), ('canceled', 'Canceled'), ('error', 'Error')], default='new', max_length=254),
        ),
        migrations.CreateModel(
            name='EmailMessageWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.JSONField()),
                ('headers', models.JSONField()),
                ('type', models.CharField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='new', max_length=127)),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.emailmessage')),
            ],
        ),
    ]
