# Generated by Django 3.2.13 on 2022-10-30 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20221030_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secondary ID', unique=True, verbose_name='UUID'),
        ),
    ]
