# Generated by Django 3.2.13 on 2022-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
