# Generated by Django 3.2.13 on 2022-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20221101_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='sender_email',
            field=models.EmailField(max_length=254),
        ),
    ]
