# Generated by Django 3.2.16 on 2023-03-17 20:21

from django.db import migrations


def get_user_name(user):
    if user.first_name and user.last_name:
        return f"{user.first_name} {user.last_name}"
    elif user.first_name:
        return user.first_name
    elif user.last_name:
        return user.last_name
    else:
        return user.email


def forwards_func(apps, schema_editor):
    User = apps.get_model("base", "User")
    Org = apps.get_model("base", "Org")
    OrgUser = apps.get_model("base", "OrgUser")
    Plan = apps.get_model("base", "Plan")
    default_plan, _ = Plan.objects.get_or_create(
        is_default=True, defaults={"name": "Default"}
    )
    for user in User.objects.all():
        org = Org(
            owner=user,
            is_personal=True,
            name=get_user_name(user),
            is_active=True,
            primary_plan=default_plan,
            default_plan=default_plan,
        )
        org.full_clean()
        org.save()

        OrgUser.objects.get_or_create(
            user=user,
            org=org,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_orgs"),
    ]

    operations = [
        migrations.RunPython(
            forwards_func, reverse_code=migrations.RunPython.noop, elidable=True
        )
    ]
