# Generated by Django 3.2.16 on 2023-03-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230317_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='org',
            field=models.ForeignKey(help_text='The active Org of the User that caused the EmailMessage to be created.', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.org'),
        ),
    ]
