# Generated by Django 3.2.16 on 2023-03-22 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_emailmessage_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='created_by',
            field=models.ForeignKey(help_text='User that caused the EmailMessage to be created.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='org',
            field=models.ForeignKey(help_text='The active Org of the User that caused the EmailMessage to be created.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.org'),
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=254)),
                ('email', models.EmailField(help_text='Email address of the invitee', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_invitations', to='base.emailmessage')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='base.org')),
            ],
        ),
    ]
