# Generated by Django 3.2.16 on 2023-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20230322_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginvitation',
            name='email_message',
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='email_messages',
            field=models.ManyToManyField(related_name='org_invitations', to='base.EmailMessage'),
        ),
    ]
