# Generated by Django 3.2.16 on 2023-05-03 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20230405_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_at', models.DateTimeField()),
                ('type', models.CharField(max_length=127)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
