# Generated by Django 4.2.3 on 2023-07-26 20:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_squashed_20230708"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orguser",
            name="joined_at",
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="emailmessagewebhook",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="emailmessagewebhook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="emailmessagewebhook",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="orginvitation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="orgsetting",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="orguser",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="orguser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="orguserousetting",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="ousetting",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="ousettingdefault",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="overriddenorgsetting",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="planorgsetting",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secondary ID",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="orginvitation",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="orgsetting",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="orguserousetting",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="ousetting",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="ousettingdefault",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="overriddenorgsetting",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="planorgsetting",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
