# Generated by Django 4.2.3 on 2023-07-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "20230711_auto_20230726_2101"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="OrgInvitation",
        ),
    ]
