# Generated by Django 4.2.3 on 2023-07-31 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "20230713_event_orginvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User that caused the EmailMessage to be created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="org",
            field=models.ForeignKey(
                blank=True,
                help_text="The active Org of the User that caused the EmailMessage to be created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.org",
            ),
        ),
    ]
