# Generated by Django 4.2.3 on 2023-08-08 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "base",
            "20230714_alter_emailmessage_created_by_alter_emailmessage_org_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OUSetting",
            new_name="OrgUserSetting",
        ),
        migrations.AlterModelOptions(
            name="orgusersetting",
            options={},
        ),
    ]
