"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os.path
from pathlib import Path
import logging.config
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env = environ.Env()

READ_DOT_ENV_FILE = env.str("DJANGO_SETTINGS_MODULE") != "config.settings.production"
if READ_DOT_ENV_FILE and os.path.exists(BASE_DIR / ".env"):
    # OS environment variables take precedence over variables from .env
    env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS: list = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "inertia",
    "django_extensions",
    "django_vite",
    # Non-core apps should come before core so layouts can be overriden.
    # core must come before admin because it overrides an admin template
    "core.apps.CoreConfig",
    # core should come before staticfiles because we override collectstatic
    "django.contrib.staticfiles",
    "django.contrib.admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "inertia.middleware.InertiaMiddleware",
    "core.middleware.DisableClientCacheMiddleware",
    "core.middleware.TimezoneMiddleware",
    "core.middleware.SetRemoteAddrFromForwardedFor",
    "core.middleware.HostUrlconfMiddleware",
    "core.middleware.InertiaUserMiddleware",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# My Additions
# ---------------------
ENVIRONMENT = env.str("DJANGO_SETTINGS_MODULE").split(".")[-1]
RENDER = False
HEROKU = False

# This is a good article for how to build custom users with the email as username
# inheriting from AbstractUser rather than AbstractUserBase:
# https://www.fomfus.com/articles/how-to-use-email-as-username-for-django-authentication-removing-the-username
AUTH_USER_MODEL = "core.User"
ATOMIC_REQUESTS = False

ADMIN_URL_PATH = env("ADMIN_URL_PATH", default="admin/")

# If someday Render passes us a request id, we can use it in the request
# logging middleware.
REQUEST_ID_HEADER = None

# EMAIL
# If there's a POSTMARK_API_KEY (for the Sandbox server), use the Postmark backend.
# Otherwise, output to the console.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
POSTMARK_API_KEY = env("POSTMARK_API_KEY", default=None)
POSTMARK_DEFAULT_STREAM_ID = env("POSTMARK_DEFAULT_STREAM_ID", default="outbound")
if POSTMARK_API_KEY:
    EMAIL_BACKEND = "postmark.django_backend.EmailBackend"
    POSTMARK_TEST_MODE = False
    POSTMARK_RETURN_MESSAGE_ID = True
MAX_SUBJECT_LENGTH = 78
EMAIL_MESSAGE_WEBHOOK_PATH = env(
    "EMAIL_MESSAGE_WEBHOOK_PATH", default="email_message_webhook/"
)

# Site Configuration - Refactor this if we implement multitenant
SITE_CONFIG = {
    "name": "Django Base",
    "logo_url_link": "",
    "logo_url": "",
    "default_from_name": "Harry Khanna",
    "default_from_email": "harry@example.com",
    "account_from_name": "Account Management",
    "account_from_email": "accounts@example.com",
    "account_reply_to_name": None,
    "account_reply_to_email": None,  # Set to None to not have any reply-to in account-related emails
    "company": "Khanna PLLC",
    "company_address": "1629 K Street NW, Suite 300",  # Set to None to skip having an address.
    "company_city_state_zip": "Washington, DC 20006",
    "contact_email": "harry@example.com",
}


# Host-based alternate urlconfs.
# If the host matches one of these, use the alternate urlconf. Otherwise, use the ROOT_URLCONF.
# Every urlconf listed here must have a health_check endpoint for Render to deploy it.
# Every urlconf listed here must also have an "index" page to avoid infinite errors when rendering the 404 page.
ROOT_URLCONF = "config.urls"
HOST_URLCONFS: dict[str, str] = {}

# Authentication
LOGIN_URL = "/user/login/"
LOGIN_REDIRECT_URL = "/user/settings/profile/"
LOGOUT_REDIRECT_URL = "/user/login/"
AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]
SESSION_COOKIE_AGE = 15_552_000  # 180 days

ORG_REQUIRED_INERTIA_COMPONENT = "core/OrgRequired"

# Google OAuth
SOCIAL_AUTH_GOOGLE_ENABLED = False
SOCIAL_AUTH_GOOGLE_CLIENT_ID = env("SOCIAL_AUTH_GOOGLE_CLIENT_ID", default=None)
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET = env("SOCIAL_AUTH_GOOGLE_CLIENT_SECRET", default=None)

# Event Handlers
EVENT_HANDLERS = {"default": "core.services.event_noop"}
EVENT_SECRET = env("EVENT_SECRET", default="insecure")

# Celery
CELERY_BROKER_URL = env("REDIS_URL", default=None)
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_TIME_LIMIT = 60  # Raise exception after 60 seconds.
CELERY_WORKER_TASK_LOG_FORMAT = "[%(name)s] at=%(levelname)s timestamp=%(asctime)s processName=%(processName)s task_id=%(task_id)s task_name=%(task_name)s %(message)s"
CELERY_WORKER_LOG_FORMAT = "[%(name)s] at=%(levelname)s timestamp=%(asctime)s processName=%(processName)s %(message)s"
CELERY_WORKER_LOG_COLOR = False
CELERY_ACCEPT_CONTENT = ["json", "pickle"]
CELERY_TASK_SERIALIZER = "json"

# django-vite
DJANGO_VITE = {
    "default": {
        "dev_mode": False,
        "manifest_path": BASE_DIR / "frontend/dist/manifest.json",
    }
}

# django-inertia
INERTIA_LAYOUT = "core/layouts/inertia.html"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": BASE_DIR / ".media/",
        },
    },
    # "backups": {
    #     "BACKEND": "django.core.files.storage.FileSystemStorage",
    #     "OPTIONS": {
    #         "location": BASE_DIR / ".backups/",
    #     },
    # },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Automated backups
ENABLE_DATABASE_BACKUPS = False
ENABLE_MEDIA_BACKUPS = False  # Not implemented yet
BACKUP_ENCRYPTION_PASSPHRASE = env(
    "BACKUP_ENCRYPTION_PASSPHRASE", default="insecure passphrase"
)

# LOGGING
LOGLEVEL = env("LOGLEVEL", default="INFO")

# See https://www.caktusgroup.com/blog/2015/01/27/Django-Logging-Configuration-logging_config-default-settings-logger/
# Django's default logger is painful and there's no good reason to merge with it.
LOGGING_CONFIG = None

logging.config.dictConfig(
    {
        "version": 1,
        "disable_existing_loggers": False,
        "filters": {"request_id": {"()": "core.filters.RequestIDFilter"}},
        "formatters": {
            "default": {
                "format": "[%(name)s] at=%(levelname)s timestamp=%(asctime)s request_id=%(request_id)s "
                + "pathname=%(pathname)s funcname=%(funcName)s lineno=%(lineno)s %(message)s",
            },
        },
        "handlers": {
            "console": {
                "level": "DEBUG",
                "class": "logging.StreamHandler",
                "filters": ["request_id"],
                "formatter": "default",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "ERROR",  # Without this, it logs as a WARNING all 4xx requests.
                "propagate": False,
            },
            "": {"handlers": ["console"], "level": LOGLEVEL},
        },
    }
)
