name: Django CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  token_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          if grep --exclude-dir={.venv,node_modules,.git,.github,.cursorrules} -rE "TODO|FIXME|console\.log"; then
               exit 1
          else
              echo "All good"
          fi

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
          npm install --prefix frontend/
          playwright install
      - name: Typecheck with mypy
        run: |
          mypy .
      - name: Test with pytest
        run: |
          VITE_PORT=3000 npm run dev --prefix frontend/ < /dev/null &
          DJANGO_ALLOW_ASYNC_UNSAFE=true VITE_PORT=3000 py.test -n auto
      # - name: Deploy to Render
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     deploy_url_web: ${{ secrets.RENDER_DEPLOY_HOOK_URL_WEB }}
      #     deploy_url_celery: ${{ secrets.RENDER_DEPLOY_HOOK_URL_CELERY }}
      #   run: |
      #     curl "$deploy_url_web"
      #     curl "$deploy_url_celery"
