name: Django CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  token_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          if grep --exclude-dir={.venv,node_modules,.git,.github} -rE "TODO|FIXME|console\.log"; then
               exit 1
          else
              echo "All good"
          fi

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: Typecheck with mypy
        run: |
          make mypy
      - name: Test with pytest
        run: |
          py.test
